runner_module: runners.runner_TDD - runner_TDD  
random_seed: 111
params:
  epochs: 200 
  device: cuda:0
  batch_size: 1 
  training_channels: 162
  image_size: 224
  warm_up_n_iters: 100

model: 
  name: models.TDD_seg_model - TDD_seg_model  
  args: 
    n_channels: 162
  ckpt_dir: /home/luojianet/ljt21/TDD/ckpts
  R: 3.0
 
transforms: 
  train: 
  - name: albumentations - ToFloat
    args:
      max_value: 286, 292, 299, 292, 299, 300, 295, 308, 296, 306, 307, 312, 305,
        314, 310, 311, 311, 314, 314, 314, 311, 319, 318, 317, 317, 320, 320, 325,
        331, 331, 332, 337, 343, 348, 352, 356, 361, 376, 369, 373, 378, 383, 386,
        396, 395, 392, 395, 400, 402, 408, 408, 416, 417, 409, 421, 427, 429, 450,
        458, 463, 470, 473, 493, 472, 479, 485, 488, 488, 477, 494, 449, 471, 482,
        497, 484, 501, 501, 502, 499, 512, 519, 463, 508, 524, 533, 533, 533, 536,
        542, 547, 545, 545, 552, 559, 510, 525, 524, 536, 543, 546, 548, 553, 549,
        555, 555, 567, 572, 563, 559, 548, 561, 560, 562, 556, 565, 565, 577, 592,
        442, 472, 494, 465, 490, 501, 526, 530, 525, 529, 540, 539, 543, 565, 574,
        577, 550, 558, 541, 521, 526, 507, 491, 480, 495, 509, 530, 552, 561, 537,
        511, 495, 502, 477, 477, 467, 451, 453, 440, 456, 474, 471, 466, 467
  - name: albumentations - Resize
    args:
      height: ${params.image_size}
      width: ${params.image_size}
      p: 1 
      interpolation: 0
  - name: albumentations.pytorch - ToTensorV2
    args:
      p: 1
  test:
  - name: albumentations - Resize
    args:
      height: ${params.image_size}
      width: ${params.image_size}
      interpolation: 0
      p: 1
  - name: albumentations.pytorch - ToTensorV2
    args:
      p: 1
datasets:
  train:
    name: datasets.HSIDataset_Training - HSIDataset_Training
    args:
      img_dir: /home/luojianet/ljt21/TDD/data/HYDICE/training_patches/img_patch_40_stride_20
      max_height: 13
      min_height: 7
  test:
    name: datasets.HSIDataset_Inferring - HSIDataset_Inferring
    args:
      img_dir:
      - /home/luojianet/ljt21/TDD/data/HYDICE/image.img
      - /home/luojianet/ljt21/TDD/data/Cri/Cri.img
      - /home/luojianet/ljt21/TDD/data/WHU-Hi-River/WHU-Hi-River.img
      - /home/luojianet/ljt21/TDD/data/AVIRIS-1/image.img
      mask_dir:
      - /home/luojianet/ljt21/TDD/data/HYDICE/mask_urban.img
      - /home/luojianet/ljt21/TDD/data/Cri/cri_mask.img
      - /home/luojianet/ljt21/TDD/data/WHU-Hi-River/Target_mask.img
      - /home/luojianet/ljt21/TDD/data/AVIRIS-1/label.img
      test_patch_sizes:
      - 10
      - 100
      - 20
      - 50
      test_pad_sizes:
      - 5
      - 100
      - 10
      - 25
      normalize:
      - true
      - true
      - false
      - true
      test_input_sizes:
      - 224
      - 224
      - 224
      - 224
      training_channels: ${params.training_channels}
dataloaders:
  train:
    name: torch.utils.data - DataLoader
    args:
      batch_size: ${params.batch_size}
      num_workers: 3
      pin_memory: true
      shuffle: true
  test:
    name: torch.utils.data - DataLoader
    args:
      batch_size: 1
      num_workers: 3
      pin_memory: true
      shuffle: false
optimizer:
  name: torch.optim - Adam
  args:
    lr: 0.0001
    weight_decay: 1.0e-05
scheduler:
  name: torch.optim.lr_scheduler - CosineAnnealingWarmRestarts
  args:
    T_0: 10
    T_mult: 2
    eta_min: 0.0001
    last_epoch: -1
